set_property SRC_FILE_INFO {cfile:d:/Prager/KC705_DDS/Mixed/k7dsp_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mmcm/mmcm.xdc rfile:../k7dsp_dds_mig.srcs/sources_1/ip/mmcm/mmcm.xdc id:1 order:EARLY scoped_inst:KC705_fmc150_inst/mmcm_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Prager/KC705_DDS/Mixed/k7dsp_dds_mig/k7dsp_dds_mig.srcs/constrs_1/imports/k7_TRD/k7dsp_rtl_tutorial.xdc rfile:../k7dsp_dds_mig.srcs/constrs_1/imports/k7_TRD/k7dsp_rtl_tutorial.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports CLK_IN1]] 0.050000000000000003
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter sysclk_p 0.050
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter ddr3_clk1_p 0.050
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of [get_pins KC705_fmc150_inst/mmcm_adac_inst/inst/mmcm_adv_inst/CLKIN1]] 0.041
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of [get_pins KC705_fmc150_inst/mmcm_inst/inst/mmcm_adv_inst/CLKIN1]] 0.050
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y10 [get_cells {KC705_fmc150_inst/adc_data_a[4].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y10 [get_cells {KC705_fmc150_inst/adc_data_a[4].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y12 [get_cells {KC705_fmc150_inst/adc_data_a[1].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y12 [get_cells {KC705_fmc150_inst/adc_data_a[1].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y14 [get_cells {KC705_fmc150_inst/adc_data_a[6].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y14 [get_cells {KC705_fmc150_inst/adc_data_a[6].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y16 [get_cells {KC705_fmc150_inst/adc_data_b[1].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y16 [get_cells {KC705_fmc150_inst/adc_data_b[1].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y18 [get_cells {KC705_fmc150_inst/adc_data_b[3].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y18 [get_cells {KC705_fmc150_inst/adc_data_b[3].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y2 [get_cells {KC705_fmc150_inst/adc_data_a[5].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y2 [get_cells {KC705_fmc150_inst/adc_data_a[5].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y20 [get_cells {KC705_fmc150_inst/adc_data_b[2].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y20 [get_cells {KC705_fmc150_inst/adc_data_b[2].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y26 [get_cells KC705_fmc150_inst/IDELAYE2_inst_ADC_CLK]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y28 [get_cells {KC705_fmc150_inst/adc_data_a[0].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y28 [get_cells {KC705_fmc150_inst/adc_data_a[0].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y30 [get_cells {KC705_fmc150_inst/adc_data_b[6].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y30 [get_cells {KC705_fmc150_inst/adc_data_b[6].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y36 [get_cells {KC705_fmc150_inst/adc_data_b[5].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y36 [get_cells {KC705_fmc150_inst/adc_data_b[5].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y38 [get_cells {KC705_fmc150_inst/adc_data_b[4].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y38 [get_cells {KC705_fmc150_inst/adc_data_b[4].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y4 [get_cells {KC705_fmc150_inst/adc_data_a[3].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y4 [get_cells {KC705_fmc150_inst/adc_data_a[3].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y6 [get_cells {KC705_fmc150_inst/adc_data_a[2].ISERDESE2_adc_cha}]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y6 [get_cells {KC705_fmc150_inst/adc_data_a[2].IDELAYE2_inst_ADC_ch_A}]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC ILOGIC_X0Y8 [get_cells {KC705_fmc150_inst/adc_data_b[0].ISERDESE2_adc_chb}]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IDELAY_X0Y8 [get_cells {KC705_fmc150_inst/adc_data_b[0].IDELAYE2_inst_ADC_ch_B}]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y70 [get_cells {KC705_fmc150_inst/dac_data[0].oserdes_data}]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y62 [get_cells {KC705_fmc150_inst/dac_data[1].oserdes_data}]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y64 [get_cells {KC705_fmc150_inst/dac_data[2].oserdes_data}]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y56 [get_cells {KC705_fmc150_inst/dac_data[3].oserdes_data}]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y54 [get_cells {KC705_fmc150_inst/dac_data[4].oserdes_data}]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y52 [get_cells {KC705_fmc150_inst/dac_data[5].oserdes_data}]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y78 [get_cells {KC705_fmc150_inst/dac_data[6].oserdes_data}]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y76 [get_cells {KC705_fmc150_inst/dac_data[7].oserdes_data}]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y58 [get_cells KC705_fmc150_inst/oserdes_clock]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X0Y60 [get_cells KC705_fmc150_inst/oserdes_frame]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property FIXED_ROUTE {{ IOB_IBUF0 RIOI_I0 RIOI_ILOGIC0_D IOI_ILOGIC0_O RIOI_I2GCLK_TOP0 HCLK_CMT_MUX_OUT_FREQ_REF0 HCLK_CMT_FREQ_REF_NS0 PLL_CLK_FREQ_BB_BUFOUT_NS0 MMCM_CLK_FREQ_BB_NS0 CMT_L_LOWER_B_CLK_FREQ_BB3 CMT_LR_LOWER_B_MMCM_CLKIN1 }} [get_nets KC705_fmc150_inst/clk_in1]
set_property src_info {type:XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC XADC_X0Y0 [get_cells u_mig_7series_0/u_mig_7series_0_mig/temp_mon_enabled.u_tempmon/xadc_supplied_temperature.XADC_inst]
