# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_1s2m/axis_interconnect_1s2m.xci
# IP: The module: 'axis_interconnect_1s2m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_1s2m/axis_interconnect_1s2m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_interconnect_1s2m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_1s2m/axis_interconnect_1s2m_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_interconnect_1s2m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_1s2m/axis_interconnect_1s2m.xci
# IP: The module: 'axis_interconnect_1s2m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_1s2m/axis_interconnect_1s2m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_interconnect_1s2m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_1s2m/axis_interconnect_1s2m_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_interconnect_1s2m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
