# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Prager/KC705_DDS/Mixed/k7dsp_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/complex_multiplier_DUC/complex_multiplier_DUC.xci
# IP: The module: 'complex_multiplier_DUC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Prager/KC705_DDS/Mixed/k7dsp_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/complex_multiplier_DUC/complex_multiplier_DUC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'complex_multiplier_DUC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Prager/KC705_DDS/Mixed/k7dsp_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/complex_multiplier_DUC/complex_multiplier_DUC.xci
# IP: The module: 'complex_multiplier_DUC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Prager/KC705_DDS/Mixed/k7dsp_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/complex_multiplier_DUC/complex_multiplier_DUC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'complex_multiplier_DUC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
