# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/UndergroundRadar/kc705_dds_mig/mig_7series_1_example/mig_7series_1_example.srcs/sources_1/ip/vio_twm_ddrx/vio_twm_ddrx.xci
# IP: The module: 'vio_twm_ddrx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/mig_7series_1_example/mig_7series_1_example.srcs/sources_1/ip/vio_twm_ddrx/vio_twm_ddrx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_twm_ddrx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/mig_7series_1_example/mig_7series_1_example.srcs/sources_1/ip/vio_twm_ddrx/vio_twm_ddrx.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_twm_ddrx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/UndergroundRadar/kc705_dds_mig/mig_7series_1_example/mig_7series_1_example.srcs/sources_1/ip/vio_twm_ddrx/vio_twm_ddrx.xci
# IP: The module: 'vio_twm_ddrx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/mig_7series_1_example/mig_7series_1_example.srcs/sources_1/ip/vio_twm_ddrx/vio_twm_ddrx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_twm_ddrx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/mig_7series_1_example/mig_7series_1_example.srcs/sources_1/ip/vio_twm_ddrx/vio_twm_ddrx.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_twm_ddrx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
