# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-220-radar-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tffg900-2

    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_ctrl_addr_decode.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_ctrl_read.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_ctrl_reg.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_ctrl_reg_bank.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_ctrl_top.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_ctrl_write.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_ar_channel.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_aw_channel.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_b_channel.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_cmd_arbiter.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_cmd_fsm.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_cmd_translator.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_fifo.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_incr_cmd.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_r_channel.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_simple_fifo.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_wrap_cmd.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_wr_cmd_fsm.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_axi_mc_w_channel.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_axic_register_slice.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_axi_register_slice.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_axi_upsizer.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_a_upsizer.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_carry_and.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_carry_latch_and.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_carry_latch_or.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_carry_or.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_command_fifo.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_comparator.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_comparator_sel.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_comparator_sel_static.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_r_upsizer.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/axi/mig_7series_v2_1_ddr_w_upsizer.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/clocking/mig_7series_v2_1_clk_ibuf.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/clocking/mig_7series_v2_1_infrastructure.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/clocking/mig_7series_v2_1_iodelay_ctrl.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/clocking/mig_7series_v2_1_tempmon.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_arb_mux.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_arb_row_col.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_arb_select.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_bank_cntrl.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_bank_common.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_bank_compare.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_bank_mach.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_bank_queue.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_bank_state.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_col_mach.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_mc.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_rank_cntrl.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_rank_common.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_rank_mach.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/controller/mig_7series_v2_1_round_robin_arb.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ecc/mig_7series_v2_1_ecc_buf.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ecc/mig_7series_v2_1_ecc_dec_fix.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ecc/mig_7series_v2_1_ecc_gen.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ecc/mig_7series_v2_1_ecc_merge_enc.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ecc/mig_7series_v2_1_fi_xor.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ip_top/mig_7series_v2_1_memc_ui_top_axi.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ip_top/mig_7series_v2_1_mem_intfc.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_byte_group_io.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_byte_lane.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_calib_top.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_if_post_fifo.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_mc_phy.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_mc_phy_wrapper.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_of_pre_fifo.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_4lanes.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_ck_addr_cmd_delay.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_dqs_found_cal.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_dqs_found_cal_hr.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_init.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_oclkdelay_cal.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_prbs_rdlvl.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_rdlvl.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_tempmon.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_top.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_wrcal.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_wrlvl.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_phy_wrlvl_off_delay.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/phy/mig_7series_v2_1_ddr_prbs_gen.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ui/mig_7series_v2_1_ui_cmd.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ui/mig_7series_v2_1_ui_rd_data.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ui/mig_7series_v2_1_ui_top.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/ui/mig_7series_v2_1_ui_wr_data.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/mig_7series_1.v
      d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/mig_7series_1/mig_7series_1/user_design/rtl/mig_7series_1_mig.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-220-radar-PC/realtime/mig_7series_1_synth.xdc
    rt::sdcChecksum
    set rt::top mig_7series_1
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-220-radar-PC/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  return -code "error" $rt::result
}
