# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0.xci
# IP: The module: 'axi_vfifo_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_vfifo_ctrl_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_vfifo_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0.xci
# IP: The module: 'axi_vfifo_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_vfifo_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_vfifo_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
