# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/kc705_ethernet_rgmii.xci
# IP: The module: 'kc705_ethernet_rgmii' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_ethernet_rgmii'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_ethernet_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_ethernet_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_ethernet_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/kc705_ethernet_rgmii.xci
# IP: The module: 'kc705_ethernet_rgmii' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_ethernet_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_ethernet_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_ethernet_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/kc705_ethernet_rgmii/synth/kc705_ethernet_rgmii_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_ethernet_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
