# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/ddc_imf2/ddc_imf2.xci
# IP: The module: 'ddc_imf2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/ddc_imf2/ddc_imf2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_imf2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/ddc_imf2/ddc_imf2.xci
# IP: The module: 'ddc_imf2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/ddc_imf2/ddc_imf2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_imf2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
