# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==vio_twm_ddrx || ORIG_REF_NAME==vio_twm_ddrx}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==mig_7series_1 || ORIG_REF_NAME==mig_7series_1}]]
set_property BUFFER_TYPE NONE -quiet [get_ports -quiet -of [get_cells -hier -filter {REF_NAME==ila_ddrx_axi || ORIG_REF_NAME==ila_ddrx_axi}]]
