# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_0/axis_interconnect_0.xci
# IP: The module: 'axis_interconnect_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_0/axis_interconnect_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_interconnect_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_0/axis_interconnect_0.xci
# IP: The module: 'axis_interconnect_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/sf_VMLinux/Projects/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/axis_interconnect_0/axis_interconnect_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_interconnect_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
