# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/duc_imf1/duc_imf1.xci
# IP: The module: 'duc_imf1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/duc_imf1/duc_imf1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'duc_imf1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/duc_imf1/duc_imf1.xci
# IP: The module: 'duc_imf1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UndergroundRadar/kc705_dds_mig/k7dsp_dds_mig.srcs/sources_1/ip/duc_imf1/duc_imf1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'duc_imf1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
